title: My Blog
email: owen.winchell@proton.me
description: Just ranting about stuff I like and dislike, hope you like it here
github_username: ThatOSDeveloper

# Build settings
remote_theme: pages-themes/hacker@v0.2.0
plugins:
- jekyll-remote-theme
