title: My Blog
email: owen.winchell@proton.me
description: >-
  Just ranting about stuff I like and dislike, hope you like it here
baseurl: "" 
github_username: ThatOSDeveloper

# Build settings
remote_theme: pages-themes/hacker@v0.2.0
plugins:
- jekyll-remote-theme

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
